"""create documents chunks qa_logs

Revision ID: a5f439213056
Revises:
Create Date: 2026-09-14 20:27:38.155239

The first migration: it creates all three tables at once.

A migration file is the history of the schema. Its value is that running these files in
order on any machine yields exactly the same tables as everywhere else, so a committed
migration is never edited -- a schema change means a new migration.

Generated by `alembic revision --autogenerate` and then hand-edited in two places, both
marked in upgrade() below.
"""

from typing import Sequence, Union

import pgvector.sqlalchemy  # added by hand: VECTOR is used below and autogenerate omits it
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5f439213056"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the tables."""
    # Added by hand: pgvector's vector type is not built into PostgreSQL, so the extension
    # has to exist first. Without this, a fresh database fails at the chunks table with
    # "type vector does not exist". IF NOT EXISTS keeps a re-run from erroring.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "qa_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("retrieved_chunk_ids", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        # 384-dimensional vector, matching EMBEDDING_DIM in app/core/config.py
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        # Database-level cascade: deleting a document removes its chunks.
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunks_document_chunk_index"),
    )
    op.create_index(op.f("ix_chunks_document_id"), "chunks", ["document_id"], unique=False)


def downgrade() -> None:
    """Drop the tables.

    The vector extension is deliberately left in place: it is a database-wide shared
    resource that other tables may rely on, and recreating it costs far less than dropping
    it by mistake. A downgrade undoes only what its own migration created.
    """
    op.drop_index(op.f("ix_chunks_document_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_table("qa_logs")
    op.drop_table("documents")
